0-custom_http_response-header

diff --git a/0x0F-load_balancer/0-custom_http_response-header b/0x0F-load_balancer/0-custom_http_response-header
--- a/0x0F-load_balancer/0-custom_http_response-header
+++ b/0x0F-load_balancer/0-custom_http_response-header
@@ -1,32 +1,84 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-# Update the package list and upgrade existing packages
-sudo apt update
-sudo apt upgrade -y
+# uncomment to see the script run in action
+#set -x
 
-# Install Nginx if it's not already installed
-if ! [ -x "$(command -v nginx)" ]; then
-  sudo apt install nginx -y
+echo -e "Updating and doing some minor checks...\n"
+
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
 fi
 
-# Create a custom Nginx configuration file to add the X-Served-By header
-echo 'server {
-    listen 80;
-    server_name localhost;
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-    location / {
-        proxy_pass http://localhost:8080; # Replace with your application server's address
-        proxy_set_header X-Served-By $HOSTNAME; # Add X-Served-By header with the hostname
-    }
-}' | sudo tee /etc/nginx/sites-available/custom_http_response_header
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
-# Create a symbolic link to enable the custom configuration
-sudo ln -s /etc/nginx/sites-available/custom_http_response_header /etc/nginx/sites-enabled/
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-# Test the Nginx configuration for syntax errors
-sudo nginx -t
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-# If the configuration is valid, reload Nginx to apply changes
-if [ $? -eq 0 ]; then
-  sudo systemctl reload nginx
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
 fi
